spring.application.name=backend

server.port=8082
# Database එකට connect වෙන්න අවශ්‍ය විස්තර
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus
spring.datasource.username=root
# Password එකක් නැති නිසා මෙතන හිස්ව තියන්න
spring.datasource.password=Ka2026/04/20

# Hibernate Settings (Tables ඉබේම හැදීමට)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect